name: flutter_app
description: "Flutter news application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  logger: ^2.0.2+1
  cached_network_image: ^3.3.1
  loading_animation_widget: ^1.2.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.4
  mobx_codegen: ^2.6.0+1
  json_annotation: ^4.6.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.0.0
  flutter_riverpod: ^2.3.3
  flutter_simple_dependency_injection: ^2.0.0
  test: ^1.24.9
  sliver_header_delegate: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true


http: any
