name: Linter Check
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Change Directory
        run: cd flutter_app
      - name: Get Dependencies
        run: flutter pub get
      - name: Generate Code
        run: dart run build_runner build
      - name: Check linter
        run: flutter analyze