name: Linter Check
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check Linter
        run: cd flutter_app & flutter analyze